### ISSUE TITLE
How to make the modal somewhat transparent?

### ISSUE THREAD

**Issue by dodalovicgran** [joshmu/periscope#1]
Is there a way to not cover the items below the modal? I like the ripgrep, but this prevents me from using your extension. 

![image](https://github.com/joshmu/periscope/assets/116893230/976b7a11-a65c-41ab-ac07-e674908084dd)

Thank You

**Comment by joshmu** [comment]
Hey @dodalovicgran 

There is no direct way to directly control the color theme from an extension that I'm aware of.

If you really wanted to you could customise your theme to support transparency for the quickpick menu globally or at a theme level via your settings.json

You could define a HEXA color where the alpha channel you can lower to create the transparency, although I would think it would be great for practical use.

```json
  "workbench.colorCustomizations": {
    "quickInput.background": "#6E85F722",
  },
```

<img width="881" alt="image" src="https://github.com/joshmu/periscope/assets/1970265/dd276f50-9550-48cc-a9ec-75afd2aee2fc">

**Comment by dodalovicgran** [comment]
Hmm...... 
It would be amazing if this search modal could be shown to the side, so that it doesn't hide the code beneath it. :thinking:

**Comment by joshmu** [comment]
If that is what you want you can simply use vscode's inbuilt project wide search which nowadays is running ripgrep behind the scenes.

As your original issue question on modal transparency is resolved I'll close this issue.

If you would like to contribute to the extension to offer a configuration option to move it to the side I'd be more than welcome to it. :)

Have a good day!
