### ISSUE TITLE
Is there a way to only search for paths and not file contents?

### ISSUE THREAD

**Issue by gabrielmaldi** [joshmu/periscope#29]
Great extension, thanks!

**Comment by joshmu** [comment]
Hey @gabrielmaldi 

The extension's main purpose is for file content searching.

Saying that I would think it would be fairly straight forward to update the extension to also support searching file paths in the future.  Not sure when I will have time to look in to that at the moment though 😅.

The extension is using **ripgrep** under the hood so it would be a matter of utilising the correct command and then passing that through to the quick pick.

A filepath lookup would be something like this:
![image](https://github.com/joshmu/periscope/assets/1970265/b66d35ac-d1d3-41fc-ad94-bfa8c3acc78b)

**Comment by joshmu** [comment]
Closing this as vscode's inbuilt behaviour is sufficient for filename search.  For now Periscope will primarily focus on file contents search only.
