### ISSUE TITLE
Fails on windows with path contains whitespace

### ISSUE THREAD

**Issue by dncc89** [joshmu/periscope#53]
Hi, thanks for great extension!

When the extensions calls rg on windows, it fails when the path is including whitespace.

Currently the command passed looks like this
`c:\Users\xxx\.vscode\extensions\joshmu.periscope-1.6.10-win32-x64\node_modules\@vscode\ripgrep\bin\rg.exe" "orbi" --line-number --column --no-heading --with-filename --color=never --json --smart-case --sortr path d:\Path with whitespace`

`PERISCOPE: d:\Path: IO error for operation on d:\Path:`

**Comment by joshmu** [comment]
Hey @dncc89 

pushed a fix for this, let me know if its still causing issues

thanks for the heads up!
