### ISSUE TITLE
Is there a way to grep in a specified directory?

### ISSUE THREAD

**Issue by liuzhishan** [joshmu/periscope#66]
My workspace is too large, so when I use periscope to grep, it takes too much time to search. However, I roughly known which folder I want to grep, so is there a way that I can specify a folder for grep ? It would be much faster under a specified directory.

**Comment by joshmu** [comment]
Hey @liuzhishan 

You can use **ripgrep** arguments to do things such as filter by a folder glob (`--iglob`) or file extension (`-t`) etc.

Easiest is probably create for yourself a `rgQueryParam` (refer to the readme docs)
It's essentially a way to declare ripgrep search definition mapped to a regex pattern match shorthand.

Add this to your **settings.json**
eg:
```json
  "periscope.rgQueryParams": [
    {
      // filter the results to a folder
      // Query: redis -m module1 => rg 'redis' --iglob '**/*module1*/**'
      "param": "--iglob '**/*$1*/**' --iglob '!**/node_modules/**'",
      "regex": "^(.+) -m ([\\w-_]+)$"
    },
  ]
```

Now when you do a query such as: "**_foo -m bar_**"
You would be searching for any file contents with **_foo_** in any folder **_bar_**

Hope that helps! :)

**Comment by liuzhishan** [comment]
Hi, @joshmu, thanks! It works perfectly.

**Comment by joshmu** [comment]
Cool, enjoy!
